name: sustain
description: An app that helps in sustainbility for climate change.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  riverpod: ^1.0.3
  freezed_annotation: ^2.0.3
  auto_route: ^4.0.1
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.15
  firebase_storage: ^10.2.16
  json_annotation: ^4.5.0
  flutter_riverpod: ^1.0.4
  flutter_hooks: ^0.18.4
  flutter_native_splash: ^2.2.8
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  introduction_screen: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  build_runner: ^2.1.10
  auto_route_generator: ^4.0.0


flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: lib/common\assets\mother-earth-day.png 
  image_dark: lib/common\assets\mother-earth-day.png 
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
      - lib/common/assets/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

